// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_b2-5BSCMlmAg9kMf3P_prjLqE7-Tvk',
    appId: '1:908117969556:web:390fab4ca63ad4d58c8281',
    messagingSenderId: '908117969556',
    projectId: 'smart-bloom-350004',
    authDomain: 'smart-bloom-350004.firebaseapp.com',
    storageBucket: 'smart-bloom-350004.firebasestorage.app',
    measurementId: 'G-FKZP6WGE7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYdseT-Ncf2zHesKm7OiFD-eAEZZeDBk',
    appId: '1:908117969556:android:16fda26496ee56fa8c8281',
    messagingSenderId: '908117969556',
    projectId: 'smart-bloom-350004',
    storageBucket: 'smart-bloom-350004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArEL4HtVGP90r6AK239NbVGqSceT4dwB8',
    appId: '1:908117969556:ios:cac9ae552659c7fd8c8281',
    messagingSenderId: '908117969556',
    projectId: 'smart-bloom-350004',
    storageBucket: 'smart-bloom-350004.firebasestorage.app',
    iosBundleId: 'com.ssyok.frontend',
  );

}